export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const PAYMENT_SETUP_SUCCESS = 'PAYMENT_SETUP_SUCCESS';
export const PAYMENT_SETUP_FAILED = 'PAYMENT_SETUP_FAILED';

export const STRIPE_CODE_MATCH = 'STRIPE_CODE_MATCH';
export const STRIPE_CODE_MISMATCH = 'STRIPE_CODE_MISMATCH';